vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=4")
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set conceallevel=1")
vim.cmd("filetype plugin indent on")
vim.api.nvim_exec("language ru_RU", true)
vim.g.mapleader = " "
